#pragma once

enum class NodeType {
    CLASS_DEC,
    SUBRNT_DEC_LIST,
    CONSTRUCTOR_DEC,
    FUNCTION_DEC,
    METHOD_DEC,
    SUBRTN_BODY,
    STATIC_VAR_DEC,
    FIELD_VAR_DEC,
    LOCAL_VAR_DEC,
    ARGUMENT_VAR_DEC,
    STATIC_VAR_DEC_LIST,
    FIELD_VAR_DEC_LIST,
    LOCAL_VAR_DEC_LIST,
    ARGUMENT_VAR_DEC_LIST,
    STATEMENT_LIST,
    LET_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    DO_STATEMENT,
    RETURN_STATEMENT,
    EXPRESSION,
    EXPRESSION_LIST,
    BINOP_EXPR,
    UNOP_EXPR,
    NEW_ARRAY_EXPR,
    DELETE_ARRAY_EXPR,
    NAME_EXPR,
    LITERAL_EXPR,
    ARRAY_MEMBER_EXPR,
    MEMBER_EXPR,
    CALL_EXPR,
};

enum class OpType {
    ADD_OP,
    SUB_OP,
    MUL_OP,
    DIV_OP,
    LOG_AND_OP,
    LOG_OR_OP,
    BIT_AND_OP,
    BIT_OR_OP,
    LSS_OP,
    GTR_OP,
    EQL_OP,
    NEG_OP,
    TILDE_OP,
};

enum class SubroutineKind {
    CONSTRUCTOR_S,
    FUNCTION_S,
    METHOD_S,
};

enum class VarModifier {
    ARG_V,
    LOCAL_V,
    STATIC_V,
    FIELD_V,
};